[package]
name = "sstui"
version = "0.1.4"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/sopho-s/stui"
homepage = "https://github.com/sopho-s/stui"
readme = "README.md"
include = [
    "**/*.rs"
]
description = "A rust tui library to allow for html like decleration of gui"

[profile.release]
debug = true

[dependencies]
sdl2 = "0.38.0"
roxmltree = "0.21.1"
crossterm = "0.29.0"
console = "0.16.3"
format_num = "0.1.0"
